# Generated by Django 5.2.8 on 2026-01-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('condition', models.CharField(max_length=50)),
                ('humidity', models.PositiveIntegerField()),
                ('wind_speed', models.FloatField(help_text='Wind speed in m/s')),
                ('api_source', models.CharField(default='openweathermap', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='trips.trip')),
            ],
        ),
    ]
