# Generated by Django 5.2.8 on 2026-03-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_initial'),
        ('trips', '0003_alter_trip_trip_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_packing_list', to='trips.trip')),
            ],
            options={
                'verbose_name': 'User Packing List',
                'verbose_name_plural': 'User Packing Lists',
            },
        ),
    ]
