# Generated by Django 5.2.8 on 2026-01-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trip_type', models.CharField(choices=[('city', 'City'), ('beach', 'Beach'), ('mountain', 'Moif untain'), ('business', 'Business')], max_length=10)),
                ('luggage_type', models.CharField(choices=[('backpack', 'Backpack'), ('small_suitcase', 'Small suitcase (≤ 10kg)'), ('large_suitcase', 'Large suitcase (> 10kg)')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
