# Generated by Django 5.2.8 on 2026-03-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('city', 'City'), ('beach', 'Beach'), ('mountain', 'Mountain'), ('business', 'Business')], max_length=10),
        ),
    ]
